// Balloon Battle stages: 6 worlds x 3 stages (stage 3 is the boss), on the
// Crazy Arcade 15 x 13 board. Maps are original; they follow CA's level-design
// rules (fixed set pieces, 50-65 % soft blocks, clear pockets at spawns).
//
// Shared legend: . floor, x soft block, # hard block, P player, e enemy spawn,
// B boss spawn (top-left of its 2 x 2), % filler under a multi-tile set piece.
// World legends below add each theme's tiles and gimmicks.

import type { BossKind, Dir, ItemKind, OpponentSlug, WorldId } from "./data";

export const COLS = 15;
export const ROWS = 13;

export type CellKind = "floor" | "hard" | "soft" | "water";

export interface CellSpec {
  kind: CellKind;
  ground?: string; // ground sprite (default: world checkerboard)
  obj?: string | string[]; // block sprite (a list picks by position)
  hide?: boolean; // bushes and tall grass hide whoever stands in them
  ice?: boolean;
  belt?: Dir;
  drain?: boolean;
  push?: boolean;
  sprinkler?: boolean;
  piece?: { sprite: string; w: number; h: number; kind: CellKind };
}

const F: CellSpec = { kind: "floor" };

export const LEGENDS: Record<WorldId, Record<string, CellSpec>> = {
  toytown: {
    "|": { kind: "floor", ground: "road_dash_v" },
    "-": { kind: "floor", ground: "road_dash_h" },
    "+": { kind: "floor", ground: "road" },
    z: { kind: "floor", ground: "zebra_v" },
    Z: { kind: "floor", ground: "zebra_h" },
    ",": { kind: "floor", ground: "plaza" },
    w: { kind: "floor", obj: "bush", hide: true },
    H: { kind: "hard", obj: ["house_blue", "house_yellow", "house_red", "shop_green"] },
    T: { kind: "hard", obj: "tree" },
    p: { kind: "hard", obj: "pine" },
    L: { kind: "hard", obj: "lamp" },
    F: { kind: "hard", obj: "fountain", ground: "plaza" },
    c: { kind: "soft", obj: "crate" },
  },
  harbor: {
    k: { kind: "soft", obj: "push_crate", push: true },
    M: { kind: "hard", obj: "mast" },
    C: { kind: "hard", obj: "cannon" },
    A: { kind: "hard", obj: "anchor" },
    o: { kind: "hard", obj: "bollard" },
    $: { kind: "hard", obj: "chest" },
    "=": { kind: "floor", ground: "deck_dark" },
    S: { kind: "hard", piece: { sprite: "ship", w: 3, h: 2, kind: "hard" } },
  },
  forest: {
    g: { kind: "floor", obj: "tallgrass", hide: true },
    T: { kind: "hard", obj: "tree_big" },
    t: { kind: "hard", obj: "tree" },
    R: { kind: "hard", obj: "rock" },
    u: { kind: "hard", obj: "stump" },
    _: { kind: "floor", ground: "path" },
    O: { kind: "water", piece: { sprite: "pond_2x2", w: 2, h: 2, kind: "water" } },
    Q: { kind: "water", piece: { sprite: "pond_3x2", w: 3, h: 2, kind: "water" } },
  },
  frost: {
    "~": { kind: "floor", ground: "ice", ice: true },
    I: { kind: "hard", obj: "igloo" },
    S: { kind: "hard", obj: "snowman" },
    c: { kind: "hard", obj: "crystal" },
    R: { kind: "hard", obj: "rocket" },
    U: { kind: "hard", obj: "ufo_wreck" },
    p: { kind: "hard", obj: "pine_snow" },
  },
  steel: {
    ">": { kind: "floor", ground: "belt_e", belt: "right" },
    "<": { kind: "floor", ground: "belt_w", belt: "left" },
    "^": { kind: "floor", ground: "belt_n", belt: "up" },
    v: { kind: "floor", ground: "belt_s", belt: "down" },
    d: { kind: "floor", ground: "drain", drain: true },
    h: { kind: "floor", ground: "hazard" },
    M: { kind: "hard", obj: ["machine", "machine_orange"] },
    K: { kind: "hard", obj: "tank" },
    S: { kind: "hard", obj: "smokestack" },
  },
  stadium: {
    A: { kind: "hard", obj: ["ad_board", "ad_board_red"] },
    b: { kind: "hard", obj: "bench" },
    s: { kind: "hard", obj: "sprinkler", sprinkler: true },
    T: { kind: "hard", obj: "trophy" },
    c: { kind: "soft", obj: "cone_stack" },
    t: { kind: "floor", ground: "track" },
    G: { kind: "hard", piece: { sprite: "goal", w: 3, h: 1, kind: "hard" } },
  },
};

export const COMMON: Record<string, CellSpec> = {
  ".": F,
  P: F,
  e: F,
  B: F,
  x: { kind: "soft" },
  "#": { kind: "hard" },
};

export interface StageDef {
  id: string; // "1-1"
  world: WorldId;
  map: string[];
  enemies: Partial<Record<OpponentSlug, number>>;
  boss?: BossKind;
  par: number; // seconds for an S rank
  time: number; // stage clock
  kit?: { balloons?: number; range?: number; speed?: number; needles?: number; kick?: boolean };
  items?: Partial<Record<ItemKind, number>>; // hidden in soft blocks (others are random)
  tip?: string; // i18n key for a one-line gameplay tip on the intro card
}

export const STAGES: StageDef[] = [
  // ---- World 1: Seoul Toy Town (Village) ----
  {
    id: "1-1",
    world: "toytown",
    map: [
      "pxxexH.|.Hxexxp",
      "xHxxcx.|.xcxxHx",
      ".xwxHxx|xxHxwx.",
      "xcxTxxx|xxxTxcx",
      "xxHxxc.|.cxxHxx",
      "H.xxL..Z..Lxx.H",
      "--z-e--+--e-z--",
      "H.xxL..Z..Lxx.H",
      "xxHxxc.|.cxxHxx",
      "xcxTxxx|xxxTxcx",
      ".xwxHxx|xxHxwx.",
      "xHxxcx.|.xcxxHx",
      "pxx.xH.P.Hx.xxp",
    ],
    enemies: { "gimpo-fc": 4, "suwon-fc": 1 },
    par: 90,
    time: 180,
    items: { balloon: 4, potion: 4, cleats: 2, needle: 1, coin: 2 },
    tip: "tipBush",
  },
  {
    id: "1-2",
    world: "toytown",
    map: [
      "xxxxHxx.xxHxxxx",
      "xTx.xxxexxx.xTx",
      "xxwxxHx.xHxxwxx",
      "Hxx.x,,,,,x.xxH",
      "xx.ex,H,H,xe.xx",
      ".xHxx,,F,,xxHx.",
      "exx.x,H,H,x.xxe",
      ".xHxx,,,,,xxHx.",
      "xx.xxx.x.xxx.xx",
      "HxwxTxx.xxTxwxH",
      "xxxx.xxexx.xxxx",
      "xTx.xHx.xHx.xTx",
      "xxxxx..P..xxxxx",
    ],
    enemies: { "gimpo-fc": 2, "suwon-fc": 2, "seongnam-fc": 2 },
    par: 120,
    time: 180,
    items: { balloon: 4, potion: 4, cleats: 3, kick: 1, needle: 1, shield: 1, coin: 2 },
    tip: "tipThief",
  },
  {
    id: "1-3",
    world: "toytown",
    map: [
      "T,,x,,,,,,,x,,T",
      ",L,,,L,,,L,,,L,",
      "x,,,,,,,,,,,,,x",
      ",,,H,,,,,,,H,,,",
      "x,,,,,,B,,,,,,x",
      ",L,,,,,,,,,,,L,",
      ",,,,,x,,,x,,,,,",
      ",L,,,,,,,,,,,L,",
      "x,,,,,,,,,,,,,x",
      ",,,H,,,,,,,H,,,",
      "x,,,,,,,,,,,,,x",
      ",L,,,L,,,L,,,L,",
      "T,,x,,,P,,,x,,T",
    ],
    enemies: { "gimpo-fc": 2 },
    boss: "swoony",
    par: 110,
    time: 240,
    kit: { balloons: 2, range: 2, speed: 1, needles: 1 },
    items: { balloon: 2, potion: 2, needle: 2, heart: 1 },
    tip: "tipBoss",
  },
  // ---- World 2: Busan Harbor (Patrit) ----
  {
    id: "2-1",
    world: "harbor",
    map: [
      "o.xxxxCeCxxxx.o",
      ".xxMxxx.xxxMxx.",
      "xx.xxx.x.xxx.xx",
      "xxxxkkx.xkkxxxx",
      "exxkxxk.kxxkxxe",
      ".xxkxxS%%xxkxx.",
      "xxxxkx%%%xkxxxx",
      "xAxxxk.e.kxxxAx",
      "xxxxxxk.kxxxxxx",
      "exxxxx.k.xxxxxe",
      "xxMxxxx.xxxxMxx",
      ".xxx$xx.xx$xxx.",
      "o.xxxx.P.xxxx.o",
    ],
    enemies: { "busan-ipark": 2, "gimhae-fc": 3 },
    par: 120,
    time: 180,
    items: { balloon: 4, potion: 4, cleats: 3, kick: 1, needle: 1, coin: 3, card: 1 },
    tip: "tipPush",
  },
  {
    id: "2-2",
    world: "harbor",
    map: [
      "e.xxxkx.xkxxx.e",
      ".#x#x#x#x#x#x#.",
      "xxxxkxx.xxkxxxx",
      "x#x#x#x#x#x#x#x",
      "xkxx.xxexx.xxkx",
      "x#x#x#...#x#x#x",
      "exx.xx.$.xx.xxe",
      "x#x#x#...#x#x#x",
      "xkxx.xxxxx.xxkx",
      "x#x#x#x#x#x#x#x",
      "xxxxkxx.xxkxxxx",
      ".#x#x#x#x#x#x#.",
      "e.xxxkx.P..kxx.",
    ],
    enemies: { "busan-ipark": 2, "gimhae-fc": 2, "gyeongnam-fc": 2 },
    par: 140,
    time: 180,
    items: { balloon: 4, potion: 4, cleats: 3, kick: 1, needle: 2, shield: 1, coin: 2, card: 1 },
    tip: "tipKnight",
  },
  {
    id: "2-3",
    world: "harbor",
    map: [
      "o.x.M.....M.x.o",
      "...x..S%%..x...",
      "x.....%%%.....x",
      "..#....B....#..",
      "x.............x",
      ".k..#.....#..k.",
      "x.............x",
      "...x..#.#..x...",
      "x.............x",
      ".k..#.....#..k.",
      "x.............x",
      "..x..x...x..x..",
      "o.....xPx.....o",
    ],
    enemies: { "busan-ipark": 1 },
    boss: "gunhami",
    par: 130,
    time: 240,
    kit: { balloons: 3, range: 3, speed: 1, needles: 1 },
    items: { balloon: 2, potion: 2, needle: 2, heart: 1 },
    tip: "tipBoss",
  },
  // ---- World 3: Fluffy Forest (Forest) ----
  {
    id: "3-1",
    world: "forest",
    map: [
      "TxxxgxxexxgxxxT",
      "xRxxxxx_xxxxxRx",
      "xxO%xxgxgxxO%xx",
      "xx%%xxx_xxx%%xx",
      "gxxxxTxxxTxxxxg",
      "exxgxxx_xxxgxxe",
      "xxxxxTx_xTxxxxx",
      "egxxxxx_xxxxxge",
      "xxQ%%xx_xxQ%%xx",
      "xx%%%xx_xx%%%xx",
      "xRxxxgx_xgxxxRx",
      "gxxxxxx_xxxxxxg",
      "TxxgxxxPxxxgxxT",
    ],
    enemies: { "cheonan-city": 3, "chungnam-asan": 2 },
    par: 130,
    time: 180,
    items: { balloon: 4, potion: 4, cleats: 3, needle: 1, shield: 1, coin: 2, card: 1 },
    tip: "tipPond",
  },
  {
    id: "3-2",
    world: "forest",
    map: [
      "exxxxxx.xxxxxxe",
      "xTxtxTxgxTxtxTx",
      "xxxxxxxxxxxxxxx",
      "gTxuxTxxxTxuxTg",
      "xxxxxx.e.xxxxxx",
      "xTxtx.Q%%.xtxTx",
      "exxxx.%%%.xxxxe",
      "xTxux.....xuxTx",
      "xxxxxxx.xxxxxxx",
      "gTxtxTxxxTxtxTg",
      "xxxxxxxxxxxxxxx",
      "xTxuxTxgxTxuxTx",
      "exxxx..P..xxxxe",
    ],
    enemies: { "cheonan-city": 2, "chungnam-asan": 2, "chungbuk-cheongju": 2 },
    par: 150,
    time: 200,
    items: { balloon: 5, potion: 5, cleats: 3, kick: 1, needle: 2, shield: 1, coin: 2, card: 1, gold: 1 },
    tip: "tipCharger",
  },
  {
    id: "3-3",
    world: "forest",
    map: [
      "TT.x.......x.TT",
      "T.............T",
      "..R..g...g..R..",
      "x.............x",
      "...g...B...g...",
      ".R...........R.",
      "x....O%...O%..x",
      ".....%%...%%...",
      ".R...........R.",
      "x..g.......g..x",
      "..R.........R..",
      "T....x...x....T",
      "TT....xPx....TT",
    ],
    enemies: { "cheonan-city": 1 },
    boss: "chaba",
    par: 150,
    time: 240,
    kit: { balloons: 3, range: 3, speed: 2, needles: 1 },
    items: { balloon: 2, potion: 2, needle: 2, heart: 1 },
    tip: "tipBoss",
  },
  // ---- World 4: Frosty Peak (Ice + a crashed spaceship) ----
  {
    id: "4-1",
    world: "frost",
    map: [
      "pxxxxxxexxxxxxp",
      "xIxxpxxxxxpxxIx",
      "xxxxxx~~~xxxxxx",
      "xpxx~~~~~~~xxpx",
      "xxx~~~~~~~~~xxx",
      "ex~~~~S~S~~~~xe",
      "xx~~~~~~~~~~~xx",
      "ex~~~~S~S~~~~xe",
      "xxx~~~~~~~~~xxx",
      "xpxx~~~~~~~xxpx",
      "xxxxxx~~~xxxxxx",
      "xIxxpxxxxxpxxIx",
      "pxxxx..P..xxxxp",
    ],
    enemies: { "paju-frontier": 3, "hwaseong-fc": 2 },
    par: 140,
    time: 200,
    items: { balloon: 5, potion: 5, cleats: 3, needle: 2, shield: 1, coin: 2, card: 1 },
    tip: "tipIce",
  },
  {
    id: "4-2",
    world: "frost",
    map: [
      "exxxcxx.xxcxxxe",
      "xRxxxx~~~xxxxRx",
      "xxx~~xx.xx~~xxx",
      "xcxx~xpxpx~xxcx",
      "xxxxxxxexxxxxxx",
      "~~xpxxUxUxxpx~~",
      "exxxxx~~~xxxxxe",
      "~~xpxxUxUxxpx~~",
      "xxxxxxxxxxxxxxx",
      "xcxx~xpxpx~xxcx",
      "xxx~~xx.xx~~xxx",
      "xRxxxx~~~xxxxRx",
      "exxxcx.P.xcxxxe",
    ],
    enemies: { "paju-frontier": 2, "hwaseong-fc": 2, "yongin-fc": 2 },
    par: 160,
    time: 200,
    items: { balloon: 5, potion: 5, cleats: 3, kick: 1, needle: 2, shield: 1, coin: 2, card: 2, gold: 1 },
    tip: "tipTeleport",
  },
  {
    id: "4-3",
    world: "frost",
    map: [
      "p.x...x.x...x.p",
      "...............",
      "x.c.........c.x",
      ".......~~......",
      "......~B~~.....",
      "x....~~~~~~...x",
      "..c..~~~~~~.c..",
      "x....~~~~~~...x",
      "......~~~~.....",
      ".......~~......",
      "x.c.........c.x",
      "...............",
      "p.x...xPx...x.p",
    ],
    enemies: { "paju-frontier": 2 },
    boss: "mars",
    par: 160,
    time: 240,
    kit: { balloons: 4, range: 4, speed: 2, needles: 1 },
    items: { balloon: 2, potion: 2, needle: 2, heart: 1 },
    tip: "tipBoss",
  },
  // ---- World 5: Gwangyang Steelworks (Factory) ----
  {
    id: "5-1",
    world: "steel",
    map: [
      "exxxxxxexxxxxxe",
      "xMxxxMxxxMxxxMx",
      "xxxdxxxxxxxdxxx",
      "xxx>>>>>>>>vxxx",
      "xMx^xxxxxxxvxMx",
      "xxx^xMxdxMxvxxx",
      "exx^xxx.xxxvxxe",
      "xxx^xMxdxMxvxxx",
      "xMx^xxxxxxxvxMx",
      "xxx^<<<<<<<<xxx",
      "xxxdxxxxxxxdxxx",
      "xMxxxMxxxMxxxMx",
      "exxxx..P..xxxxe",
    ],
    enemies: { "jeonnam-dragons": 2, "daegu-fc": 2, "gyeongnam-fc": 1 },
    par: 160,
    time: 200,
    items: { balloon: 5, potion: 5, cleats: 3, kick: 1, needle: 2, shield: 1, coin: 2, card: 2 },
    tip: "tipBelt",
  },
  {
    id: "5-2",
    world: "steel",
    map: [
      "hhxxxxx.xxxxxhh",
      "hKxxKxxexxKxxKh",
      "xxxxxdxxxdxxxxx",
      "xxSxxxxxxxxxSxx",
      "xxxx>>>>>>vxxxx",
      "exdx^xMxMxvxdxe",
      "xxxx^xx.xxvxxxx",
      "exdx^xMxMxvxdxe",
      "xxxx^<<<<<<xxxx",
      "xxSxxxxxxxxxSxx",
      "xxxxxdxxxdxxxxx",
      "hKxxKxxxxxKxxKh",
      "hhxxx..P..xxxhh",
    ],
    enemies: { "jeonnam-dragons": 2, "daegu-fc": 2, "busan-ipark": 1, "chungbuk-cheongju": 1 },
    par: 180,
    time: 220,
    items: { balloon: 5, potion: 5, cleats: 3, kick: 1, needle: 2, shield: 2, coin: 2, card: 2, gold: 1 },
    tip: "tipDrain",
  },
  {
    id: "5-3",
    world: "steel",
    map: [
      "KK..x.....x..KK",
      "K.............K",
      "..M..d...d..M..",
      "x.............x",
      "...h...B...h...",
      ".M...........M.",
      "x..d.......d..x",
      ".M...........M.",
      "...h.......h...",
      "x.............x",
      "..M..d...d..M..",
      "K....x...x....K",
      "KK....xPx....KK",
    ],
    enemies: { "daegu-fc": 1 },
    boss: "cheolryong",
    par: 170,
    time: 240,
    kit: { balloons: 4, range: 4, speed: 2, needles: 2 },
    items: { balloon: 2, potion: 2, needle: 2, heart: 1 },
    tip: "tipBoss",
  },
  // ---- World 6: Grand Stadium ----
  {
    id: "6-1",
    world: "stadium",
    map: [
      "AxxxxxxexxxxxxA",
      "xxcxxsxxxsxxcxx",
      "xbxxxxxxxxxxxbx",
      "xxxx.xxxxx.xxxx",
      "exsxxxxAxxxxsxe",
      "xxxxxx...xxxxxx",
      "AxxxxA.T.AxxxxA",
      "xxxxxx...xxxxxx",
      "exsxxxxAxxxxsxe",
      "xxxx.xxxxx.xxxx",
      "xbxxxxxxxxxxxbx",
      "xxcxxsx.xsxxcxx",
      "Axxxx..P..xxxxA",
    ],
    enemies: { "ansan-greeners": 2, "suwon-samsung-bluewings": 2, "cheonan-city": 1, "gimhae-fc": 1 },
    par: 180,
    time: 220,
    items: { balloon: 5, potion: 5, cleats: 3, kick: 1, needle: 2, shield: 2, coin: 2, card: 2, gold: 1 },
    tip: "tipSprinkler",
  },
  {
    id: "6-2",
    world: "stadium",
    map: [
      "AAAAAAG%%AAAAAA",
      "xxxxxx...xxxxxx",
      "exxsxxxxxxxsxxe",
      "xxxxxxxxxxxxxxx",
      "xAxxxxxxxxxxxAx",
      "xxxxxx.e.xxxxxx",
      "sxxxxx.T.xxxxxs",
      "xxxxxx...xxxxxx",
      "xAxxxxxxxxxxxAx",
      "xxxxxxxxxxxxxxx",
      "exxsxxxxxxxsxxe",
      "xxxxxx...xxxxxx",
      "xxxxxx.P.xxxxxx",
    ],
    enemies: { "ansan-greeners": 2, "suwon-samsung-bluewings": 2, "yongin-fc": 1, "jeonnam-dragons": 1, "seongnam-fc": 1 },
    par: 200,
    time: 240,
    items: { balloon: 6, potion: 6, cleats: 3, kick: 1, needle: 2, shield: 2, coin: 3, card: 2, gold: 1, ginseng: 1 },
    tip: "tipHunter",
  },
  {
    id: "6-3",
    world: "stadium",
    map: [
      "AAAAAAG%%AAAAAA",
      "...............",
      "..s.........s..",
      "x....x...x....x",
      "...A...B...A...",
      "...............",
      "x.s....x....s.x",
      "...............",
      "...A.......A...",
      "x....x...x....x",
      "..s.........s..",
      "...............",
      "x.....xPx.....x",
    ],
    enemies: { "ansan-greeners": 2 },
    boss: "aguileon",
    par: 200,
    time: 300,
    kit: { balloons: 5, range: 5, speed: 3, needles: 2 },
    items: { balloon: 2, potion: 2, needle: 2, heart: 2, ginseng: 1 },
    tip: "tipFinal",
  },
];

export function stageIndex(id: string): number {
  return STAGES.findIndex((s) => s.id === id);
}

export function specFor(world: WorldId, ch: string): CellSpec {
  return LEGENDS[world][ch] ?? COMMON[ch] ?? F;
}
