' Auto-generated by scripts\silence-existing-task.ps1.
' Do not edit by hand and do not commit. Hardcoded paths to this workspace.
Option Explicit
Dim WshShell, exitCode, q, cmd
q = Chr(34)
Set WshShell = CreateObject("WScript.Shell")
WshShell.CurrentDirectory = "C:\Andy Herman\Coding Projects (Local)\seoul_eland_digest"
cmd = q & "C:\Windows\system32\cmd.exe" & q & " /c "C:\Andy Herman\Coding Projects (Local)\seoul_eland_digest\run_k2_news_scrub.bat""
' Run window style 0 (SW_HIDE), bWaitOnReturn = True so the exit code
' propagates back to Task Scheduler.
exitCode = WshShell.Run(cmd, 0, True)
Set WshShell = Nothing
WScript.Quit exitCode