export type PawLocale = "en" | "pt";

export const PAW_STRINGS = {
  en: {
    pageTitle: "Lenyang's Paw Hunt | Seoul E-Land Digest",
    pageDescription: "Follow Lenyang's paw prints across Seoul E-Land Digest in a 21 clue treasure hunt.",
    eyebrow: "레냥의 발자국 찾기",
    title: "Lenyang's Paw Hunt",
    intro:
      "Lenyang wandered through the Digest and left 21 tiny paw prints behind. Solve the clues, visit the pages, and collect every print to earn a Detective Lenyang certificate.",
    howTitle: "How it works",
    chapterLabel: "Chapter",
    steps: [
      "Read a clue and browse the Digest for the page it describes.",
      "Tap the paw print when you find it. Progress stays only on this device.",
      "Finish each chapter to unlock the next set of clues.",
    ],
    progress: "paws found",
    showHint: "Show hint",
    hideHint: "Hide hint",
    found: "Found",
    notFound: "Not found yet",
    locked: "Locked until the previous chapter is complete",
    visit: "Visit the page",
    reset: "Reset progress",
    confirmReset: "Tap again to confirm reset",
    rewardTitle: "Detective Lenyang certificate",
    rewardLocked: "Find all 21 paws to unlock your certificate.",
    nameLabel: "Detective name",
    drawCertificate: "Update certificate",
    download: "Download PNG",
    share: "Share",
    credit: "Lenyang and Leoul belong to Seoul E-Land FC and are used with permission.",
    ariaPaw: "Collect Lenyang paw print",
    toastFound: (count: number, total: number) => `Paw ${count} of ${total} found!`,
    toastStart: "You found one of Lenyang's paw prints! There are 21 hidden on the Digest. Start the hunt",
    startHunt: "Start the hunt",
    huntPage: "Hunt page",
    completed: "All paws found. Lenyang names you a Digest detective.",
    certificateTitle: "Detective Lenyang",
    certificateSubtitle: "completed Lenyang's Paw Hunt",
    certificateCount: "21 of 21 paws found",
    certificateDate: "Date",
  },
  pt: {
    pageTitle: "Caça às patas da Lenyang | Seoul E-Land Digest",
    pageDescription: "Siga as patinhas da Lenyang pelo Seoul E-Land Digest em uma caça ao tesouro de 21 pistas.",
    eyebrow: "레냥의 발자국 찾기",
    title: "Caça às patas da Lenyang",
    intro:
      "A Lenyang passeou pelo Digest e deixou 21 patinhas pelo caminho. Resolva as pistas, visite as páginas e colete todas para ganhar um certificado de Detetive Lenyang.",
    howTitle: "Como funciona",
    chapterLabel: "Capítulo",
    steps: [
      "Leia uma pista e navegue pelo Digest até a página certa.",
      "Toque na patinha quando encontrar. O progresso fica só neste aparelho.",
      "Complete cada capítulo para liberar o próximo bloco de pistas.",
    ],
    progress: "patinhas encontradas",
    showHint: "Mostrar dica",
    hideHint: "Esconder dica",
    found: "Encontrada",
    notFound: "Ainda não encontrada",
    locked: "Bloqueado até completar o capítulo anterior",
    visit: "Visitar a página",
    reset: "Zerar progresso",
    confirmReset: "Toque de novo para confirmar",
    rewardTitle: "Certificado de Detetive Lenyang",
    rewardLocked: "Encontre as 21 patinhas para liberar seu certificado.",
    nameLabel: "Nome do detetive",
    drawCertificate: "Atualizar certificado",
    download: "Baixar PNG",
    share: "Compartilhar",
    credit: "Lenyang e Leoul pertencem ao Seoul E-Land FC e são usados com permissão.",
    ariaPaw: "Coletar patinha da Lenyang",
    toastFound: (count: number, total: number) => `Patinha ${count} de ${total} encontrada!`,
    toastStart: "Você encontrou uma das patinhas da Lenyang! Há 21 escondidas no Digest. Comece a caça",
    startHunt: "Começar a caça",
    huntPage: "Página da caça",
    completed: "Todas as patinhas encontradas. A Lenyang te nomeia detetive do Digest.",
    certificateTitle: "Detetive Lenyang",
    certificateSubtitle: "completou a Caça às patas da Lenyang",
    certificateCount: "21 de 21 patinhas encontradas",
    certificateDate: "Data",
  },
} as const;
