// Mascot Kart track themes: sky, light, fog, ground and the painted surfaces for each venue.
import type { RoadKind, VergeKind, WallKind } from "./textures";

export interface Theme {
  id: string;
  skyTop: string;
  skyHorizon: string;
  skyBottom: string;
  fog: string;
  fogNear: number;
  fogFar: number;
  sun: { color: string; intensity: number; dir: [number, number, number] };
  hemi: { sky: string; ground: string; intensity: number };
  ground: VergeKind | "water";
  verge: VergeKind;
  road: RoadKind;
  edge: string; // road edge line colour
  curb: [string, string];
  boards: string[];
  boardColors: [string, string][];
  wallHeight: Partial<Record<WallKind, number>>;
  embankment: string; // colour of the sloped sides under raised road
  skyline: { mountains: string; city: string; windows: string; density: number; towers?: ("nseoul" | "lotte" | "63")[]; sea?: boolean };
  night?: boolean;
}

const WALL_H: Partial<Record<WallKind, number>> = { tires: 1.1, boards: 1.3, rail: 1.05, stone: 2.4, fence: 2.1, hedge: 1.5, wood: 1.2 };

export const THEMES: Record<string, Theme> = {
  mokdong: {
    id: "mokdong",
    skyTop: "#5fb8ff",
    skyHorizon: "#c9ecff",
    skyBottom: "#e9f7ff",
    fog: "#cfeeff",
    fogNear: 180,
    fogFar: 900,
    sun: { color: "#fff4dc", intensity: 2.2, dir: [0.4, 1, 0.25] },
    hemi: { sky: "#cfe9ff", ground: "#6a8f58", intensity: 1.35 },
    ground: "grass",
    verge: "grass",
    road: "asphalt",
    edge: "#f2b705",
    curb: ["#1b2446", "#f2b705"],
    boards: ["SEOUL E-LAND", "레울 & 레냥", "MASCOT KART", "목동 · MOKDONG", "서울의 노래"],
    boardColors: [["#1b2446", "#f2b705"], ["#ffffff", "#1b2446"], ["#f2b705", "#1b2446"], ["#1b2446", "#ffffff"]],
    wallHeight: WALL_H,
    embankment: "#8fb06a",
    skyline: { mountains: "#8fb3d9", city: "#9fb6cf", windows: "#dbe7f3", density: 1.1, towers: ["nseoul", "63"] },
  },
  hangang: {
    id: "hangang",
    skyTop: "#070d2e",
    skyHorizon: "#26356e",
    skyBottom: "#3b3f7a",
    fog: "#1b2554",
    fogNear: 160,
    fogFar: 780,
    sun: { color: "#b7c6ff", intensity: 1.1, dir: [-0.3, 1, 0.5] },
    hemi: { sky: "#5566b8", ground: "#1c2444", intensity: 1.2 },
    ground: "grass",
    verge: "grass",
    road: "asphalt",
    edge: "#38bdf8",
    curb: ["#38bdf8", "#ffffff"],
    boards: ["한강 · HAN RIVER", "여의도 YEOUIDO", "MASCOT KART", "반포대교", "SEOUL E-LAND"],
    boardColors: [["#0f1a4a", "#7dd3fc"], ["#f472b6", "#ffffff"], ["#1b2446", "#f2b705"], ["#0ea5e9", "#ffffff"]],
    wallHeight: WALL_H,
    embankment: "#3c5a44",
    skyline: { mountains: "#1b2658", city: "#141d44", windows: "#fde68a", density: 1.3, towers: ["63", "nseoul", "lotte"] },
    night: true,
  },
  namsan: {
    id: "namsan",
    skyTop: "#6aa9ff",
    skyHorizon: "#ffd6a0",
    skyBottom: "#ffe9cc",
    fog: "#f6dcc0",
    fogNear: 150,
    fogFar: 760,
    sun: { color: "#ffd7a8", intensity: 2.1, dir: [-0.7, 0.8, 0.2] },
    hemi: { sky: "#ffe2c2", ground: "#4f7a45", intensity: 1.25 },
    ground: "grass",
    verge: "grass",
    road: "asphalt",
    edge: "#ef4444",
    curb: ["#ef4444", "#ffffff"],
    boards: ["남산 · NAMSAN", "N SEOUL TOWER", "MASCOT KART", "서울타워", "SEOUL E-LAND"],
    boardColors: [["#b91c1c", "#ffffff"], ["#ffffff", "#b91c1c"], ["#1b2446", "#f2b705"]],
    wallHeight: WALL_H,
    embankment: "#6d8a4a",
    skyline: { mountains: "#b99c8a", city: "#c8a894", windows: "#ffe4c4", density: 0.9, towers: ["lotte"] },
  },
  suwon: {
    id: "suwon",
    skyTop: "#70b6ff",
    skyHorizon: "#f3e2c0",
    skyBottom: "#f8efdc",
    fog: "#efe0c4",
    fogNear: 170,
    fogFar: 820,
    sun: { color: "#fff0d0", intensity: 2.2, dir: [0.5, 1, -0.3] },
    hemi: { sky: "#f6ead0", ground: "#8a7a48", intensity: 1.3 },
    ground: "autumn",
    verge: "autumn",
    road: "brick",
    edge: "#b45309",
    curb: ["#b91c1c", "#f5f0e6"],
    boards: ["수원 화성", "SUWON HWASEONG", "팔달문", "MASCOT KART", "수원 FC · 수원 삼성"],
    boardColors: [["#7c2d12", "#fde68a"], ["#1d4ed8", "#ffffff"], ["#b91c1c", "#ffffff"]],
    wallHeight: WALL_H,
    embankment: "#9a8a5a",
    skyline: { mountains: "#a9b7a0", city: "#c3b8a2", windows: "#f5ecd8", density: 0.7 },
  },
  busan: {
    id: "busan",
    skyTop: "#2f9cff",
    skyHorizon: "#bfe8ff",
    skyBottom: "#e2f6ff",
    fog: "#c8ecff",
    fogNear: 200,
    fogFar: 950,
    sun: { color: "#fffbe8", intensity: 2.4, dir: [0.3, 1, 0.4] },
    hemi: { sky: "#d6f1ff", ground: "#c8b07a", intensity: 1.35 },
    ground: "sand",
    verge: "sand",
    road: "asphalt",
    edge: "#ef4444",
    curb: ["#c8102e", "#ffffff"],
    boards: ["부산 · BUSAN", "광안대교", "GWANGALLI", "MASCOT KART", "BUSAN IPARK"],
    boardColors: [["#c8102e", "#ffffff"], ["#0369a1", "#ffffff"], ["#ffffff", "#c8102e"]],
    wallHeight: WALL_H,
    embankment: "#d8c08a",
    skyline: { mountains: "#86a9c8", city: "#9fb4c8", windows: "#e0f2fe", density: 1.2, sea: true },
  },
  jinhae: {
    id: "jinhae",
    skyTop: "#8cc8ff",
    skyHorizon: "#ffe4ee",
    skyBottom: "#fff2f6",
    fog: "#ffe8f0",
    fogNear: 150,
    fogFar: 760,
    sun: { color: "#fff2f4", intensity: 2.1, dir: [0.2, 1, 0.5] },
    hemi: { sky: "#ffe7f0", ground: "#6f9a58", intensity: 1.35 },
    ground: "pink",
    verge: "pink",
    road: "asphalt",
    edge: "#f472b6",
    curb: ["#f472b6", "#ffffff"],
    boards: ["진해 군항제", "JINHAE", "벚꽃 CHERRY BLOSSOM", "MASCOT KART", "GYEONGNAM FC"],
    boardColors: [["#f472b6", "#ffffff"], ["#ffffff", "#db2777"], ["#be123c", "#ffffff"]],
    wallHeight: WALL_H,
    embankment: "#7aa05e",
    skyline: { mountains: "#9fb7a8", city: "#e3cdd6", windows: "#fff1f5", density: 0.55 },
  },
  gwangyang: {
    id: "gwangyang",
    skyTop: "#5a78c8",
    skyHorizon: "#ffb870",
    skyBottom: "#ffd8a0",
    fog: "#f4b884",
    fogNear: 150,
    fogFar: 760,
    sun: { color: "#ffc48a", intensity: 2.0, dir: [-0.8, 0.6, 0.1] },
    hemi: { sky: "#ffcf9a", ground: "#56606e", intensity: 1.25 },
    ground: "concrete",
    verge: "concrete",
    road: "concrete",
    edge: "#facc15",
    curb: ["#facc15", "#1f2937"],
    boards: ["광양 · GWANGYANG", "JEONNAM DRAGONS", "전남 드래곤즈", "MASCOT KART", "PORT"],
    boardColors: [["#facc15", "#1f2937"], ["#1f2937", "#facc15"], ["#dc2626", "#ffffff"]],
    wallHeight: WALL_H,
    embankment: "#6b7280",
    skyline: { mountains: "#9a7f8e", city: "#7d6f78", windows: "#ffd8a8", density: 0.9, sea: true },
  },
  daegu: {
    id: "daegu",
    skyTop: "#ffb347",
    skyHorizon: "#ffe7a8",
    skyBottom: "#fff4d6",
    fog: "#ffe6b0",
    fogNear: 160,
    fogFar: 780,
    sun: { color: "#fff0c0", intensity: 2.6, dir: [0.1, 1, 0.2] },
    hemi: { sky: "#fff0c8", ground: "#b08a52", intensity: 1.4 },
    ground: "sand",
    verge: "dirt",
    road: "asphalt",
    edge: "#f97316",
    curb: ["#f97316", "#ffffff"],
    boards: ["대구 · DAEGU", "대프리카 DAEFRICA", "83 TOWER", "MASCOT KART", "DAEGU FC"],
    boardColors: [["#0ea5e9", "#ffffff"], ["#f97316", "#ffffff"], ["#ffffff", "#0369a1"]],
    wallHeight: WALL_H,
    embankment: "#c8a068",
    skyline: { mountains: "#c9a27a", city: "#d8b894", windows: "#fff3d6", density: 0.95 },
  },
};
